#!/bin/bash
while true; do
osascript -e 'tell application "System Events" to keystroke "w" using command down'
osascript -e 'tell application "System Events" to keystroke "q" using command down'
osascript -e 'tell application "System Events" to keystroke "q" using command down'
osascript -e 'tell application "System Events" to keystroke "q" using command down'
sleep 60
done
