#!/bin/bash
while true; do
var=`killall -v "Microsoft Word" | wc -l`
var+=`killall -v "Microsoft Powerpoint" | wc -l`
var+=`killall -v "Keynote" | wc -l`
var+=`killall -v "Pages" | wc -l`
var+=`killall -v "Numbers" | wc -l`
#Misc Apps
var+=`killall -v iBooks | wc -l`
var+=`killall -v GarageBand | wc -l`
var+=`killall -v "App Store" | wc -l`
var+=`killall -v "iTunes" | wc -l`
var+=`killall -v "Java" | wc -l`
#Other
var+=`killall -v "Activity Monitor" | wc -l`
var+=`killall -v "Finder" | wc -l`
#var+=`killall -v "Terminal" | wc -l`
#Web Browsing
killall Safari
killall Chrome
killall Firefox
echo var
if [ $var -gt 0 ]; then osascript -e 'tell app "System Events" to display dialog "This application is not permitted."'; fi
done
cd /Applications; find *.app -d | grep \w*.app$
