#!/bin/bash
while true; do
#Office Apps
var=$((`killall -v "Microsoft Word" | wc -l` + `killall -v "Microsoft PowerPoint" | wc -l` + `killall -v "Keynote" | wc -l` + `killall -v "Pages" | wc -l` + `killall -v "Numbers" | wc -l`))
#Misc Apps
var+=$((`killall -v iBooks | wc -l` + 0))
var+=$((`killall -v GarageBand | wc -l` + 0))
var+=$((`killall -v "App Store" | wc -l` + 0))
var+=$((`killall -v "iTunes" | wc -l` + 0))
var+=$((`killall -v "Java" | wc -l` + 0))
#Other
var+=$((`killall -v "Activity Monitor" | wc -l` + 0))
#var+=$((`killall -v "Finder" | wc -l` + 0))
var+=$((`killall -v "Terminal" | wc -l` + 0))
var+=$((`killall -v "System Preferences" | wc -l` + 0))
#Web Browsing
killall Safari
killall "Google Chrome"
killall Firefox
if [ $var -gt 0 ]; then
osascript -e 'tell app "System Events" to display dialog "This application is not permitted."'
fi
done
cd /Applications; find *.app -d | grep \w*.app$
